apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.images.master.name }}
  labels:
    jmeter_mode: "{{ .Values.images.master.jmeter_mode }}"
spec:
  replicas: {{ .Values.images.master.replica }}
  selector:
    matchLabels:
      jmeter_mode: {{ .Values.images.master.jmeter_mode }}
  template:
    metadata:
      labels:
        jmeter_mode: {{ .Values.images.master.jmeter_mode }}
    spec:
      containers:
      - name: jmeter-{{ .Values.images.master.jmeter_mode }}
        image: '{{ .Values.images.master.repo }}:{{ .Values.images.master.tag }}'
        imagePullPolicy: {{ .Values.images.master.pullPolicy }}
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: {{ .Values.images.master.volumeMounts_name }}
            mountPath: /{{ .Values.images.master.volumeMounts_mountPath }}
            subPath: '{{ .Values.images.master.volumeMounts_mountPath }}'
        ports:
        - containerPort: {{ .Values.images.master.containerPort }}
      volumes:
      - name: {{ .Values.images.master.volumeMounts_name }}
        configMap:
         name: {{ .Values.images.master.volume_configMap_name }}
