apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.images.slave.name }}-svc
  labels:
    jmeter_mode: {{ .Values.images.slave.jmeter_mode }}
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: {{ .Values.images.slave.jmeter_mode }}